// English content for the Mommy Makeover landing page.
// Quiz option `value`s are canonical English and are what the CRM receives on both pages.
module.exports = {
  lang: "en",
  path: "/",
  otherLang: { code: "ES", href: "/es/" },
  title: "Mommy Makeover in Miami from $7,500 | Xiluet Aesthetic Surgery",
  description:
    "Tummy tuck, breast lift or augmentation, and liposuction in one surgery. Preliminary quote after your surgeon reviews your photos. Free 60-second evaluation.",
  ogTitle: "Mommy Makeover in Miami from $7,500",

  header: { cta: "See if you qualify → 60 sec", logoAlt: "Xiluet mark", brand: "Xiluet", brandSub: "AESTHETIC SURGERY" },

  thankYou: { path: "/thank-you/", title: "Thank you | Xiluet Aesthetic Surgery", eyebrow: "EVALUATION RECEIVED", h1: "Your surgeon has your answers.", sub: "Your next step is in the card. We'll be in touch within 24–48 hours." },

  hero: {
    eyebrow: "MOMMY MAKEOVER · MIAMI, FL",
    h1Before: "Mommy Makeover in Miami",
    oldPrice: "$8,900",
    from: "from",
    newPrice: "$7,500",
    sub: "Tummy tuck, breast lift or augmentation, and liposuction in one surgery, with a written quote, a recovery plan built around your kids, and a surgeon you meet before you decide anything.",
    ctaPrimary: "See if you qualify → 60 seconds",
    ctaWhatsApp: "Chat on WhatsApp",
    waHeroMessage: "Hi, I'd like to know more about the Mommy Makeover in Miami.",
    trust: ["Free evaluation", "Financing available", "Board-certified surgeons"],
    promise: "Your consultation is with your surgeon, not a salesperson.",
  },

  quiz: {
    back: "← Back",
    badge: "FREE EVALUATION · 60 SEC",
    questionOf: "QUESTION {n} OF 8",
    continueLabel: "Continue",
    submitLabel: "Get my free evaluation →",
    sending: "Sending…",
    stateLabel: "STATE",
    cityLabel: "CITY (OPTIONAL)",
    cityPlaceholder: "Miami",
    nameLabel: "FULL NAME",
    phoneLabel: "PHONE",
    phonePlaceholder: "(305) 555-0123",
    emailLabel: "EMAIL",
    consent: "By continuing you agree to be contacted by phone, SMS or WhatsApp.",
    nameFallback: "there",
    backHome: "← Back to the page",
    outsideUS: "Outside the US",
    steps: [
      { id: "procedures", multi: true, q: 1, title: "Which procedures are you interested in?", hint: "Choose everything that applies.",
        options: [["Tummy tuck", "tummy_tuck"], ["Breast lift", "breast_lift"], ["Breast augmentation", "breast_augmentation"], ["Liposuction", "liposuction"], ["Not sure, let the surgeon recommend", "not_sure"]] },
      { id: "timing", q: 2, title: "When would you like to have surgery?",
        options: [["ASAP", "asap"], ["1–3 months", "1_3_months"], ["3–6 months", "3_6_months"], ["Just researching", "researching"]] },
      { id: "travel", q: 3, title: "Can you travel to our clinic in Miami?",
        options: [["I'm in Miami/South FL", "miami_south_fl"], ["Yes, from elsewhere in Florida", "florida"], ["Yes, from another state", "other_state"], ["No", "no"]] },
      { id: "age", q: 4, title: "Are you 18 or older?", options: [["Yes", "yes"], ["No", "no"]] },
      { id: "postpartum", q: 4, title: "Are you done having children, at least 6 months postpartum, and no longer breastfeeding?",
        options: [["Yes", "yes"], ["Not yet", "not_yet"], ["Not sure", "not_sure"]] },
      { id: "smoke", q: 4, title: "Do you smoke or vape?",
        options: [["No", "no"], ["Yes", "yes"], ["Yes, but I'd stop before surgery", "yes_would_stop"]] },
      { id: "pay", q: 5, title: "How do you plan to pay?",
        options: [["Cash/savings", "cash"], ["Financing", "financing"], ["A mix", "mix"], ["Not sure", "not_sure"]] },
      { id: "credit", q: 6, title: "Approximate credit score?", showIfPay: ["financing", "mix", "not_sure"],
        options: [["720+", "720_plus"], ["680–719", "680_719"], ["620–679", "620_679"], ["Below 620", "below_620"], ["Don't know", "unknown"]] },
      { id: "location", q: 7, type: "location", title: "Where are you located?" },
      { id: "contact", q: 8, type: "contact", title: "Where should your surgeon send your evaluation?" },
    ],
    qualified: {
      title: "Thank you, {name}. One last step for your surgeon.",
      text: "Send 4 photos so your surgeon can evaluate your case: front · left side · right side · back. In a bra and underwear or as you feel comfortable, standing straight, natural light, arms relaxed. Phone photos are perfect.",
      silhouettes: ["FRONT", "LEFT SIDE", "RIGHT SIDE", "BACK"],
      privacy: "🔒 Private. Seen only by your surgical team. Never used for marketing without your written consent.",
      waButton: "Send my photos on WhatsApp",
      waMessage: "Hi, I'm {name}. I just completed the Mommy Makeover evaluation and I'm sending my photos.",
      uploadToggle: "Upload them here instead",
      uploadSlots: ["FRONT", "LEFT", "RIGHT", "BACK"],
      uploadSubmit: "Submit photos",
      uploadSuccess: "Photos received. Your surgeon will review them and you'll hear from us within 24–48 hours.",
      uploadError: "We couldn't upload the photos. Please send them on WhatsApp instead.",
      nextLabel: "WHAT HAPPENS NEXT",
      nextSteps: ["photos", "surgeon review", "preliminary quote in 24–48h", "$250 deposit + consultation", "treatment plan + final quote", "surgery date"],
      call: "Prefer to call?",
    },
    nurture: {
      title: "You're on our list, {name}.",
      text: "A patient coordinator will reach out with next steps, financing options and, if it's \"not yet,\" exactly what \"yes\" would take.",
      waButton: "Chat on WhatsApp",
      waMessage: "Hi, I'm {name}. I just completed the Mommy Makeover evaluation.",
      call: "Prefer to call?",
    },
    notFit: {
      title: "Thank you for your honesty.",
      travel: "Our surgeries are performed in Miami. If your plans change, we'd love to help.",
      age: "Our procedures are for patients 18 and older. When the time is right, we'd love to help.",
      waButton: "Chat on WhatsApp anyway",
      waMessage: "Hi, I'm {name}. I just completed the Mommy Makeover evaluation.",
      restart: "Start over",
    },
  },

  what: {
    eyebrow: "WHAT IS A MOMMY MAKEOVER",
    h2: "Your body did something extraordinary. This is how you get it back.",
    p: "Pregnancy stretches skin, separates the abdominal muscles, and changes the breasts in ways that no amount of diet, planks or \"bouncing back\" can reverse. A Mommy Makeover is one surgery, one recovery and one plan that addresses all of it at once.",
    imgAlt: "Confident woman by the pool",
    cards: ["Tummy Tuck", "Breast Lift", "Breast Augmentation (optional)", "Liposuction"],
    note: "Your surgeon builds the combination for you. Not every woman needs all four.",
  },

  process: {
    h2: "From photos to surgery date, without pressure.",
    steps: [
      ["01", "📸", "Send 4 photos from your phone", "front, sides, back. Private, seen only by your surgical team."],
      ["02", "🩺", "Your surgeon evaluates them", "and tells you honestly if you're a candidate and what they'd recommend."],
      ["03", "📄", "Preliminary quote in 24–48h", "based on your photos, so you know where you stand before you book anything."],
      ["04", "📅", "Book your consultation", "$250 deposit reserves your appointment with the surgeon. Credited to your total."],
      ["05", "💬", "Meet your surgeon at the office", "treatment plan, analysis and final written quote, all before anything is scheduled. Bring every question."],
      ["06", "🌴", "Surgery in Miami, recovery with our team", "follow-ups included; virtual check-ins if you travel home."],
    ],
    cta: "See if you qualify → 60 seconds",
  },

  results: {
    h2: "Results That Speak For Themselves",
    items: [
      ["Breast augmentation + lipo + BBL", "Dr. Benjamin Liliav"],
      ["Tummy tuck + lipo + BBL", "Dr. Benjamin Liliav"],
      ["Lipo with BBL", "Dr. Benjamin Liliav"],
      ["Breast lift, no implants", "Dr. Marina Zorrilla"],
      ["Breast augmentation + extended tummy tuck", "Dr. Marina Zorrilla"],
      ["Breast lift with reduction, no implant", "Dr. Marina Zorrilla"],
      ["Tummy tuck + breast lift + silicone implants", "Dr. Marina Zorrilla"],
      ["Extended tummy tuck + breast augmentation", "Dr. Mel Ortega"],
      ["Extended tummy tuck + breast lift", "Dr. Mel Ortega"],
      ["Extended tummy tuck + breast lift", "Dr. Mel Ortega"],
    ],
    disclaimer: "Individual results vary. Photos shared with written patient consent.",
  },

  stories: { eyebrow: "STORIES", h2: "What they'd tell a friend.", caption: "Xiluet patient", playLabel: "Play video" },

  surgeons: {
    eyebrow: "THE SURGEONS",
    h2: "Your consultation is with the person who operates on you.",
    p: "In many Miami clinics you meet a coordinator and see the surgeon for the first time on the morning of surgery. Not here. Your surgeon reviews your photos, writes your plan, does your consultation, and sees you at every follow-up.",
    list: [
      ["Dr. Benjamin Liliav, MD", "BOARD-CERTIFIED PLASTIC SURGEON", "Dr. Benjamin Liliav, MD, FACS is a double board-certified plastic surgeon with over 20 years of experience, specializing in natural-looking results."],
      ["Dr. Marina Zorrilla, MD", "COSMETIC SURGEON", "Dr. Astrid Marina Zorrilla (\"Dr. Marina\") is a bilingual cosmetic surgeon specializing in women's aesthetic procedures, providing personalized care."],
      ["Dr. Felippe Sartorato, DO", "PLASTIC AND RECONSTRUCTIVE SURGEON", "Dr. Felippe Sartorato is a plastic and reconstructive surgeon specializing in aesthetic surgery and personalized patient care."],
      ["Madeline Vazquez", "A.P.R.N.", "Madeline Vazquez, A.P.R.N. specializes in aesthetic treatments and wellness therapies, delivering personalized care with compassion and expertise."],
    ],
    license: "Verify license ↗",
    band: "If you ever feel rushed or sold to, tell us. That's not how this works.",
  },

  pricing: {
    eyebrow: "TRANSPARENT PRICING",
    h2: "What \"from $7,500\" means. In writing.",
    p: "Every quote is itemized, line by line. Here's the standard Mommy Makeover:",
    tagLabel: "MOMMY MAKEOVER",
    oldPrice: "$8,900",
    newPrice: "from $7,500",
    includedTitle: "Included",
    includedCount: "7 ITEMS",
    included: [
      "Surgeon's fee for tummy tuck, breast lift or augmentation, and liposuction",
      "Accredited operating room and anesthesia",
      "Breast implants, when augmentation is part of your plan",
      "Pre-op labs and medical clearance",
      "Compression garments",
      "All post-op visits with your surgeon for 12 months",
      "Drain removal and post-op medication kit",
    ],
    notIncludedTitle: "Not included",
    notIncludedSub: "so there are no surprises",
    notIncluded: ["Travel and lodging", "Additional procedures your surgeon may recommend", "Prescription medications", "Recovery-house / nursing care if you want it"],
    callout: "Your surgeon reviews your photos and gives you a preliminary quote. Your final price is confirmed in writing at your consultation, with your treatment plan, before anything is scheduled.",
    cta: "Get my written quote →",
  },

  recovery: {
    eyebrow: "RECOVERY, HONESTLY",
    h2: "When can you pick up your kids again?",
    p: "Nobody shows you the in-between. We do, because it's what you'll actually plan around.",
    phases: [
      ["WEEK 1", "Rest in a recliner, walk short laps every few hours. Someone with you 24/7."],
      ["WEEKS 2–3", "Desk work and driving. Still no lifting over 10 lbs."],
      ["WEEKS 4–6", "Cleared for lifting and exercise. Yes, you can pick them up."],
      ["MONTHS 3–6", "Swelling mostly gone. Final result."],
    ],
  },

  travel: {
    eyebrow: "TRAVELING PATIENTS",
    h2: "From Orlando, Tampa, Atlanta or anywhere.",
    cards: [
      "Plan 7–10 days in Miami. Fly home after your week-1 check.",
      "Bring a companion for the first 3 days, or we'll connect you with a licensed recovery house.",
      "Follow-ups from home are by video with your surgeon.",
      "You get a packing and recovery checklist before you book.",
    ],
  },

  faq: {
    h2: "Your questions, answered straight.",
    items: [
      ["How much does a Mommy Makeover really cost here?", "From $7,500 for the standard Mommy Makeover. You get a preliminary quote after your surgeon reviews your photos, and your final itemized quote at your consultation. What's not included is listed above."],
      ["Will I meet the surgeon before surgery?", "Yes. A $250 deposit books your consultation at our office, where your surgeon reviews your case, gives you your treatment plan and final quote, and answers every question before anything is scheduled."],
      ["How bad is the pain?", "The first 2–3 days are the hardest; most patients are off strong pain medication within 3–5 days. Your surgeon will explain the pain plan."],
      ["When can I lift my kids?", "No lifting over ~10 lbs for about 6 weeks. Plan help. See the timeline above."],
      ["How long am I out of work?", "Desk work ~2 weeks; physical work 4–6 weeks."],
      ["Will I have drains? A scar?", "Most tummy tucks use drains for the first few days; your surgeon will tell you exactly how long. The scar sits low, hidden by underwear; we'll show you where before surgery."],
      ["Am I a candidate if I've had a C-section?", "Usually yes. The tummy tuck incision typically incorporates the old scar."],
      ["Do I need to be done having kids?", "We strongly recommend it. Another pregnancy can undo the results."],
      ["Is there a deposit?", "Yes. A $250 deposit is required to book your consultation with the surgeon, and it is credited toward your total. The photo evaluation and preliminary quote are free."],
      ["Do I need to live in Miami?", "No. See \"Traveling patients.\""],
    ],
  },

  final: {
    h2: "Find out in 60 seconds if this is right for you, and what it would cost.",
    cta: "Start the quiz",
    sub: "Free photo evaluation by your surgeon. The $250 deposit is only to book your consultation.",
  },

  visit: {
    h2: "Visit us in Miami",
    addressLabel: "ADDRESS",
    address: "7390 W Flagler St, Miami, FL 33144",
    hoursLabel: "HOURS",
    hours: "Mon–Fri 9 AM–6 PM · Sat 9 AM–2 PM · Sun closed",
    phoneLabel: "PHONE",
    officeAlt: "Xiluet reception",
    mapTitle: "Map",
  },

  footer: {
    skylineAlt: "Miami skyline",
    line: "Xiluet Aesthetic Surgery · 7390 W Flagler St, Miami, FL 33144 · (305) 615-4200",
    privacy: "Privacy Policy",
    terms: "Terms",
    disclaimer: "Results vary by patient. Preliminary quote after photo review; final quote at consultation.",
  },
};
