// Spanish content for the Mommy Makeover landing page.
// Quiz option `value`s stay canonical English so the CRM receives the same values on both pages.
module.exports = {
  lang: "es",
  path: "/es/",
  otherLang: { code: "EN", href: "/" },
  title: "Mommy Makeover en Miami desde $7,500 | Xiluet Aesthetic Surgery",
  description:
    "Abdominoplastia, levantamiento o aumento de senos y liposucción en una sola cirugía. Cotización preliminar después de que tu cirujano revise tus fotos. Evaluación gratis en 60 segundos.",
  ogTitle: "Mommy Makeover en Miami desde $7,500",

  header: { cta: "Mira si calificas → 60 seg", logoAlt: "Logo de Xiluet", brand: "Xiluet", brandSub: "AESTHETIC SURGERY" },

  thankYou: { path: "/es/gracias/", title: "Gracias | Xiluet Aesthetic Surgery", eyebrow: "EVALUACIÓN RECIBIDA", h1: "Tu cirujano ya tiene tus respuestas.", sub: "Tu siguiente paso está en la tarjeta. Te contactamos en 24–48 horas." },

  hero: {
    eyebrow: "MOMMY MAKEOVER · MIAMI, FL",
    h1Before: "Mommy Makeover en Miami",
    oldPrice: "$8,900",
    from: "desde",
    newPrice: "$7,500",
    sub: "Abdominoplastia, levantamiento o aumento de senos y liposucción en una sola cirugía, con cotización por escrito, un plan de recuperación pensado para tus hijos y un cirujano que conoces antes de decidir nada.",
    ctaPrimary: "Mira si calificas → 60 segundos",
    ctaWhatsApp: "Escríbenos por WhatsApp",
    waHeroMessage: "Hola, quiero saber más sobre el Mommy Makeover en Miami.",
    trust: ["Evaluación gratis", "Financiamiento disponible", "Cirujanos certificados"],
    promise: "Tu consulta es con tu cirujano, no con un vendedor.",
  },

  quiz: {
    back: "← Atrás",
    badge: "EVALUACIÓN GRATIS · 60 SEG",
    questionOf: "PREGUNTA {n} DE 8",
    continueLabel: "Continuar",
    submitLabel: "Recibir mi evaluación gratis →",
    sending: "Enviando…",
    stateLabel: "ESTADO",
    cityLabel: "CIUDAD (OPCIONAL)",
    cityPlaceholder: "Miami",
    nameLabel: "NOMBRE COMPLETO",
    phoneLabel: "TELÉFONO",
    phonePlaceholder: "(305) 555-0123",
    emailLabel: "EMAIL",
    consent: "Al continuar aceptas ser contactada por teléfono, SMS o WhatsApp.",
    nameFallback: "mamá",
    backHome: "← Volver a la página",
    outsideUS: "Fuera de EE. UU.",
    steps: [
      { id: "procedures", multi: true, q: 1, title: "¿Qué procedimientos te interesan?", hint: "Elige todo lo que aplique.",
        options: [["Abdominoplastia", "tummy_tuck"], ["Levantamiento de senos", "breast_lift"], ["Aumento de senos", "breast_augmentation"], ["Liposucción", "liposuction"], ["No estoy segura, que el cirujano recomiende", "not_sure"]] },
      { id: "timing", q: 2, title: "¿Cuándo te gustaría operarte?",
        options: [["Lo antes posible", "asap"], ["1–3 meses", "1_3_months"], ["3–6 meses", "3_6_months"], ["Solo estoy investigando", "researching"]] },
      { id: "travel", q: 3, title: "¿Puedes viajar a nuestra clínica en Miami?",
        options: [["Vivo en Miami/Sur de FL", "miami_south_fl"], ["Sí, desde otra parte de Florida", "florida"], ["Sí, desde otro estado", "other_state"], ["No", "no"]] },
      { id: "age", q: 4, title: "¿Tienes 18 años o más?", options: [["Sí", "yes"], ["No", "no"]] },
      { id: "postpartum", q: 4, title: "¿Ya no planeas más embarazos, pasaron 6+ meses del parto y ya no amamantas?",
        options: [["Sí", "yes"], ["Todavía no", "not_yet"], ["No estoy segura", "not_sure"]] },
      { id: "smoke", q: 4, title: "¿Fumas o vapeas?",
        options: [["No", "no"], ["Sí", "yes"], ["Sí, pero lo dejaría antes de la cirugía", "yes_would_stop"]] },
      { id: "pay", q: 5, title: "¿Cómo planeas pagar?",
        options: [["Efectivo/ahorros", "cash"], ["Financiamiento", "financing"], ["Una combinación", "mix"], ["No estoy segura", "not_sure"]] },
      { id: "credit", q: 6, title: "¿Tu puntaje de crédito aproximado?", showIfPay: ["financing", "mix", "not_sure"],
        options: [["720+", "720_plus"], ["680–719", "680_719"], ["620–679", "620_679"], ["Menos de 620", "below_620"], ["No lo sé", "unknown"]] },
      { id: "location", q: 7, type: "location", title: "¿Dónde te encuentras?" },
      { id: "contact", q: 8, type: "contact", title: "¿A dónde te enviamos la evaluación de tu cirujano?" },
    ],
    qualified: {
      title: "Gracias, {name}. Un último paso para tu cirujano.",
      text: "Envía 4 fotos para que tu cirujano evalúe tu caso: frente · lado izquierdo · lado derecho · espalda. En brasier y ropa interior o como te sientas cómoda, de pie y derecha, con luz natural y brazos relajados. Fotos de celular están perfectas.",
      silhouettes: ["FRENTE", "LADO IZQUIERDO", "LADO DERECHO", "ESPALDA"],
      privacy: "🔒 Privadas. Solo las ve tu equipo quirúrgico. Nunca se usan en publicidad sin tu consentimiento escrito.",
      waButton: "Enviar mis fotos por WhatsApp",
      waMessage: "Hola, soy {name}. Acabo de completar la evaluación de Mommy Makeover y envío mis fotos.",
      uploadToggle: "Prefiero subirlas aquí",
      uploadSlots: ["FRENTE", "IZQ.", "DER.", "ESPALDA"],
      uploadSubmit: "Enviar fotos",
      uploadSuccess: "Fotos recibidas. Tu cirujano las revisará y te contactaremos en 24–48 horas.",
      uploadError: "No pudimos subir las fotos. Por favor envíalas por WhatsApp.",
      nextLabel: "QUÉ SIGUE",
      nextSteps: ["fotos", "revisión del cirujano", "cotización preliminar en 24–48h", "depósito de $250 + consulta", "plan de tratamiento + cotización final", "fecha de cirugía"],
      call: "¿Prefieres llamar?",
    },
    nurture: {
      title: "Ya estás en nuestra lista, {name}.",
      text: "Una coordinadora te contactará con los siguientes pasos, opciones de financiamiento y, si es \"todavía no\", exactamente qué haría falta para el \"sí\".",
      waButton: "Escríbenos por WhatsApp",
      waMessage: "Hola, soy {name}. Acabo de completar la evaluación de Mommy Makeover.",
      call: "¿Prefieres llamar?",
    },
    notFit: {
      title: "Gracias por tu honestidad.",
      travel: "Nuestras cirugías se realizan en Miami. Si tus planes cambian, nos encantaría ayudarte.",
      age: "Nuestros procedimientos son para pacientes de 18 años o más. Cuando sea el momento, nos encantaría ayudarte.",
      waButton: "Escríbenos por WhatsApp de todas formas",
      waMessage: "Hola, soy {name}. Acabo de completar la evaluación de Mommy Makeover.",
      restart: "Empezar de nuevo",
    },
  },

  what: {
    eyebrow: "QUÉ ES UN MOMMY MAKEOVER",
    h2: "Tu cuerpo hizo algo extraordinario. Así lo recuperas.",
    p: "El embarazo estira la piel, separa los músculos abdominales y cambia los senos de formas que ninguna dieta, plancha o \"recuperación natural\" puede revertir. Un Mommy Makeover es una sola cirugía, una sola recuperación y un solo plan que resuelve todo a la vez.",
    imgAlt: "Mujer segura junto a la piscina",
    cards: ["Abdominoplastia", "Levantamiento de senos", "Aumento de senos (opcional)", "Liposucción"],
    note: "Tu cirujano arma la combinación para ti. No toda mujer necesita las cuatro.",
  },

  process: {
    h2: "De las fotos a la fecha de cirugía, sin presión.",
    steps: [
      ["01", "📸", "Envía 4 fotos desde tu celular", "frente, lados, espalda. Privadas, solo las ve tu equipo quirúrgico."],
      ["02", "🩺", "Tu cirujano las evalúa", "y te dice con honestidad si eres candidata y qué recomienda."],
      ["03", "📄", "Cotización preliminar en 24–48h", "basada en tus fotos, para que sepas dónde estás antes de reservar nada."],
      ["04", "📅", "Reserva tu consulta", "un depósito de $250 aparta tu cita con el cirujano. Se descuenta del total."],
      ["05", "💬", "Conoce a tu cirujano en la clínica", "plan de tratamiento, análisis y cotización final por escrito, todo antes de programar nada. Trae todas tus preguntas."],
      ["06", "🌴", "Cirugía en Miami, recuperación con nuestro equipo", "seguimientos incluidos; citas virtuales si regresas a tu estado."],
    ],
    cta: "Mira si calificas → 60 segundos",
  },

  results: {
    h2: "Resultados que hablan por sí solos",
    items: [
      ["Aumento de senos + lipo + BBL", "Dr. Benjamin Liliav"],
      ["Abdominoplastia + lipo + BBL", "Dr. Benjamin Liliav"],
      ["Lipo con BBL", "Dr. Benjamin Liliav"],
      ["Levantamiento de senos, sin implantes", "Dr. Marina Zorrilla"],
      ["Aumento de senos + abdominoplastia extendida", "Dr. Marina Zorrilla"],
      ["Levantamiento con reducción, sin implante", "Dr. Marina Zorrilla"],
      ["Abdominoplastia + levantamiento + implantes de silicona", "Dr. Marina Zorrilla"],
      ["Abdominoplastia extendida + aumento de senos", "Dr. Mel Ortega"],
      ["Abdominoplastia extendida + levantamiento de senos", "Dr. Mel Ortega"],
      ["Abdominoplastia extendida + levantamiento de senos", "Dr. Mel Ortega"],
    ],
    disclaimer: "Los resultados varían. Fotos compartidas con consentimiento escrito de la paciente.",
  },

  stories: { eyebrow: "HISTORIAS", h2: "Lo que le dirían a una amiga.", caption: "Paciente de Xiluet", playLabel: "Reproducir video" },

  surgeons: {
    eyebrow: "LOS CIRUJANOS",
    h2: "Tu consulta es con la persona que te va a operar.",
    p: "En muchas clínicas de Miami conoces a un coordinador y ves al cirujano por primera vez la mañana de la cirugía. Aquí no. Tu cirujano revisa tus fotos, escribe tu plan, hace tu consulta y te ve en cada seguimiento.",
    list: [
      ["Dr. Benjamin Liliav, MD", "CIRUJANO PLÁSTICO CERTIFICADO", "El Dr. Benjamin Liliav, MD, FACS, es cirujano plástico con doble certificación y más de 20 años de experiencia, especializado en resultados de aspecto natural."],
      ["Dr. Marina Zorrilla, MD", "CIRUJANA COSMÉTICA", "La Dra. Astrid Marina Zorrilla (\"Dra. Marina\") es cirujana cosmética bilingüe especializada en procedimientos estéticos para la mujer, con atención personalizada."],
      ["Dr. Felippe Sartorato, DO", "CIRUJANO PLÁSTICO Y RECONSTRUCTIVO", "El Dr. Felippe Sartorato es cirujano plástico y reconstructivo especializado en cirugía estética y atención personalizada."],
      ["Madeline Vazquez", "A.P.R.N.", "Madeline Vazquez, A.P.R.N., se especializa en tratamientos estéticos y terapias de bienestar, con atención personalizada, empatía y experiencia."],
    ],
    license: "Verificar licencia ↗",
    band: "Si en algún momento te sientes presionada o \"vendida\", dínoslo. Así no trabajamos.",
  },

  pricing: {
    eyebrow: "PRECIO TRANSPARENTE",
    h2: "Qué significa \"desde $7,500\". Por escrito.",
    p: "Cada cotización viene detallada, punto por punto. Este es el Mommy Makeover estándar:",
    tagLabel: "MOMMY MAKEOVER",
    oldPrice: "$8,900",
    newPrice: "desde $7,500",
    includedTitle: "Incluye",
    includedCount: "7 PUNTOS",
    included: [
      "Honorarios del cirujano por abdominoplastia, levantamiento o aumento de senos y liposucción",
      "Quirófano acreditado y anestesia",
      "Implantes de senos, cuando el aumento forma parte de tu plan",
      "Laboratorios y evaluación médica preoperatoria",
      "Fajas postoperatorias",
      "Todas las citas de seguimiento con tu cirujano durante 12 meses",
      "Retiro de drenajes y kit de medicamentos postoperatorios",
    ],
    notIncludedTitle: "No incluye",
    notIncludedSub: "para que no haya sorpresas",
    notIncluded: ["Viaje y hospedaje", "Procedimientos adicionales que tu cirujano recomiende", "Medicamentos con receta", "Casa de recuperación o enfermería, si la deseas"],
    callout: "Tu cirujano revisa tus fotos y te da una cotización preliminar. Tu precio final se confirma por escrito en tu consulta, junto con tu plan de tratamiento, antes de programar nada.",
    cta: "Recibir mi cotización por escrito →",
  },

  recovery: {
    eyebrow: "RECUPERACIÓN, SIN FILTROS",
    h2: "¿Cuándo vas a poder cargar a tus hijos otra vez?",
    p: "Nadie te muestra el proceso intermedio. Nosotros sí, porque es lo que de verdad vas a tener que planear.",
    phases: [
      ["SEMANA 1", "Descansas en un sillón reclinable y caminas tramos cortos cada pocas horas. Alguien contigo 24/7."],
      ["SEMANAS 2–3", "Trabajo de escritorio y manejar. Todavía nada de cargar más de 10 libras."],
      ["SEMANAS 4–6", "Alta para cargar peso y hacer ejercicio. Sí, ya puedes cargarlos."],
      ["MESES 3–6", "La inflamación casi desaparece. Resultado final."],
    ],
  },

  travel: {
    eyebrow: "PACIENTES QUE VIAJAN",
    h2: "Desde Orlando, Tampa, Atlanta o donde estés.",
    cards: [
      "Planea 7–10 días en Miami. Regresa después de tu revisión de la semana 1.",
      "Ven con un acompañante los primeros 3 días, o te conectamos con una casa de recuperación con licencia.",
      "Tus seguimientos desde casa son por video con tu cirujano.",
      "Recibes una lista de qué empacar y cómo prepararte antes de reservar.",
    ],
  },

  faq: {
    h2: "Tus preguntas, respondidas sin rodeos.",
    items: [
      ["¿Cuánto cuesta realmente un Mommy Makeover aquí?", "Desde $7,500 por el Mommy Makeover estándar. Recibes una cotización preliminar después de que tu cirujano revise tus fotos, y tu cotización final detallada en tu consulta. Lo que no incluye está arriba."],
      ["¿Conozco al cirujano antes de la cirugía?", "Sí. Un depósito de $250 reserva tu consulta en nuestra clínica, donde tu cirujano revisa tu caso, te entrega tu plan de tratamiento y cotización final, y responde todas tus preguntas antes de programar nada."],
      ["¿Qué tanto duele?", "Los primeros 2–3 días son los más difíciles; la mayoría deja los analgésicos fuertes en 3–5 días. Tu cirujano te explica el plan de manejo del dolor."],
      ["¿Cuándo puedo cargar a mis hijos?", "Nada de más de ~10 libras por unas 6 semanas. Planea ayuda. Mira el cronograma arriba."],
      ["¿Cuánto tiempo sin trabajar?", "Trabajo de oficina ~2 semanas; trabajo físico 4–6 semanas."],
      ["¿Tendré drenajes? ¿Cicatriz?", "La mayoría de las abdominoplastias usan drenajes los primeros días; tu cirujano te dirá exactamente cuánto tiempo. La cicatriz queda baja, oculta por la ropa interior; te mostramos dónde antes de operar."],
      ["¿Soy candidata si tuve cesárea?", "Generalmente sí. La incisión suele incorporar la cicatriz anterior."],
      ["¿Debo haber terminado de tener hijos?", "Lo recomendamos mucho. Otro embarazo puede deshacer los resultados."],
      ["¿Hay que dejar un depósito?", "Sí. Se requiere un depósito de $250 para reservar tu consulta con el cirujano, y se descuenta del total. La evaluación de fotos y la cotización preliminar son gratis."],
      ["¿Tengo que vivir en Miami?", "No. Mira \"Pacientes que viajan\"."],
    ],
  },

  final: {
    h2: "Descubre en 60 segundos si esto es para ti, y cuánto costaría.",
    cta: "Empezar el quiz",
    sub: "Evaluación gratis de tus fotos por el cirujano. El depósito de $250 es solo para reservar tu consulta.",
  },

  visit: {
    h2: "Visítanos en Miami",
    addressLabel: "DIRECCIÓN",
    address: "7390 W Flagler St, Miami, FL 33144",
    hoursLabel: "HORARIO",
    hours: "Lun–Vie 9 AM–6 PM · Sáb 9 AM–2 PM · Dom cerrado",
    phoneLabel: "TELÉFONO",
    officeAlt: "Recepción de Xiluet",
    mapTitle: "Mapa",
  },

  footer: {
    skylineAlt: "Vista de Miami",
    line: "Xiluet Aesthetic Surgery · 7390 W Flagler St, Miami, FL 33144 · (305) 615-4200",
    privacy: "Política de privacidad",
    terms: "Términos",
    disclaimer: "Los resultados varían según la paciente. Cotización preliminar tras revisar tus fotos; cotización final en consulta.",
  },
};
